name: jd_mobile
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  provider: ^6.0.5
  dio: ^4.0.6
  dio_log: ^2.0.4
  pretty_dio_logger: ^1.1.1
  retrofit: ^3.3.1
  get_it: ^7.2.0
  json_serializable: ^6.6.0
  google_fonts: ^4.0.1
  intl: ^0.18.0
  package_info_plus: ^3.0.1
  introduction_screen: ^3.1.4
  awesome_snackbar_content: ^0.1.0
  flutter_otp_text_field: ^1.1.1
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  retrofit_generator: ^4.2.0
  build_runner: ^2.3.3
  json_annotation: ^4.8.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/others/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
